# Generated by Django 3.2.21 on 2023-11-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerLearningAPP', '0002_auto_20231115_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='gptSim',
            field=models.FloatField(null=True, verbose_name='与GPT文本的相似度'),
        ),
        migrations.AddField(
            model_name='answer',
            name='otherSim',
            field=models.FloatField(null=True, verbose_name='与其他答案的相似度'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='isAppealed',
            field=models.IntegerField(null=True, verbose_name='0位完成,1完成'),
        ),
    ]
