# Generated by Django 3.2.21 on 2023-11-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerLearningAPP', '0003_auto_20231117_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='endTime',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='standAns',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='startTime',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='finalScore',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
