# Generated by Django 3.2.21 on 2023-11-17 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PeerLearningAPP', '0004_auto_20231117_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='startTime',
        ),
    ]
