# Generated by Django 3.2.21 on 2023-11-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerLearningAPP', '0005_auto_20231117_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='homworkDes',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
