# Generated by Django 3.2.21 on 2023-11-18 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PeerLearningAPP', '0007_auto_20231118_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='homworkDes',
            new_name='homeworkDes',
        ),
    ]
